[package]
name = "talkladok"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
failure = "0.1.5"
reqwest = "0.9.13"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
